module.exports = {
  roomTypes: {
    PUBLIC: "public",
    PRIVATE: "private",
    TOURNAMENT: "tournament",
    PRACTICE: "practice",
  },
  roomStates: {
    SEARCHING: "searching",
    WAITING: "waiting",
    WAITING_BOT_FILL: "waiting_bot_fill",
    STARTING: "starting",
    IN_PROGRESS: "in_progress",
    SETTLEMENT_PENDING: "settlement_pending",
    COMPLETED: "completed",
    CANCELLED: "cancelled",
    ABANDONED: "abandoned",
  },
  playerTypes: {
    HUMAN: "human",
    BOT: "bot",
  },
  socketEvents: {
    client: {
      JOIN_QUEUE: "ludo.queue.join",
      LEAVE_ROOM: "ludo.room.leave",
      READY: "ludo.room.ready",
      ROLL_DICE: "ludo.game.roll_dice",
      MOVE_TOKEN: "ludo.game.move_token",
      COMPLETE_MATCH: "ludo.match.complete",
      CANCEL_MATCH: "ludo.match.cancel",
      RECONNECT: "ludo.session.reconnect",
    },
    server: {
      ROOM_WAITING: "ludo.room.waiting",
      PLAYER_JOINED: "ludo.room.player_joined",
      BOT_JOINED: "ludo.room.bot_joined",
      COUNTDOWN: "ludo.room.countdown",
      STARTING: "ludo.room.starting",
      SNAPSHOT: "ludo.game.snapshot",
      TURN_STARTED: "ludo.game.turn_started",
      DICE_ROLLED: "ludo.game.dice_rolled",
      TOKEN_MOVED: "ludo.game.token_moved",
      TURN_MISSED: "ludo.game.turn_missed",
      PLAYER_FINISHED: "ludo.game.player_finished",
      RESULT: "ludo.game.result",
      ERROR: "ludo.error",
    },
  },
};
