/******************API HTTP CODES **************************/
const HTTP_OK = 200;
const HTTP_UNAUTHORIZED = 401;
const HTTP_FORBIDDEN = 403;
const HTTP_NOT_FOUND = 404;
const HTTP_METHOD_NOT_ALLOWED = 405;
const HTTP_BLANK = 407;
const HTTP_INVALID = 411;
const HTTP_NOT_ACCEPTABLE = 406;
const HTTP_SERVER_ERROR = 500;
const HTTP_SWITCH_PROTOCOL = 101;
const HTTP_WIN = 102;
const HTTP_LOOSER = 103;
const HTTP_INSUFFIENT_PAYMENT = 402;
const HTTP_ALREADY_USED = 226;
const HTTP_NO_CONTENT = 204;
const HTTP_TIME_REMAINING = 202;



module.exports = {
    HTTP_OK,
    HTTP_UNAUTHORIZED,
    HTTP_FORBIDDEN,
    HTTP_NOT_FOUND,
    HTTP_METHOD_NOT_ALLOWED,
    HTTP_BLANK,
    HTTP_INVALID,
    HTTP_NOT_ACCEPTABLE,
    HTTP_SERVER_ERROR,
    HTTP_SWITCH_PROTOCOL,
    HTTP_WIN,
    HTTP_LOOSER,
    HTTP_INSUFFIENT_PAYMENT,
    HTTP_ALREADY_USED,
    HTTP_NO_CONTENT,
    HTTP_TIME_REMAINING

}