const express = require("express");
const router = express.Router();

const auth = require("./auth");
const dragonTiger = require("./dragonTiger");
const aviator = require("./aviator");
const userRoutes = require("./userRouter");
const roulette = require("./roulette");
const trippleFun = require("./trippleFun");
const colorPrediction = require("./colorPrediction");
const colorPrediction1Min = require("./colorPrediction1Min");
const colorPrediction3Min = require("./colorPrediction3Min");
const colorPrediction5Min = require("./colorPrediction5Min");
const rummyPoint = require("./rummyPoint");
const rummyPool = require("./rummyPool");
const rummyDeal = require("./rummyDeal");
const rummyTournament = require("./rummyTournament");
const sevenUp = require("./sevenUp");
const headTail = require("./headTail");
const animalRoulette = require("./animalRoulette");
const carRoulette = require("./carRoulette");
const anderBahar = require("./anderBahar");
const redBlack = require("./redBlack");
const jackpot = require("./jackpot");
const jhandiMunda = require("./jhandiMunda");
const threeDice = require('./threeDice')
const baccarat = require("./baccarat");
const teenpatti = require("./teenpatti");
const slotGame = require("./slotGame");
const iconRoulette = require('./iconRoulette');

router.use("/auth", auth);
router.use("/DragonTiger", dragonTiger);
router.use("/aviator", aviator);
router.use("/user", userRoutes);
router.use("/roulette", roulette);
router.use("/trippleFun", trippleFun);
router.use("/ColorPrediction", colorPrediction);
router.use("/ColorPrediction1Min", colorPrediction1Min);
router.use("/ColorPrediction3Min", colorPrediction3Min);
router.use("/ColorPrediction5Min", colorPrediction5Min);
router.use("/rummy", rummyPoint);
router.use("/RummyPool", rummyPool);
router.use("/RummyDeal", rummyDeal);
router.use("/rummy-tournament", rummyTournament);
router.use("/sevenup", sevenUp);
router.use("/headtail", headTail);
router.use("/animalRoulette", animalRoulette);
router.use("/carRoulette", carRoulette);
router.use("/anderBahar", anderBahar);
router.use("/redBlack", redBlack);
router.use("/jackpot", jackpot);
router.use("/jhandiMunda", jhandiMunda);
router.use('/threeDice', threeDice);
router.use("/baccarat", baccarat);
router.use("/teenpatti", teenpatti);
router.use('/iconRoulette', iconRoulette);
router.use("/slotGame", slotGame);

module.exports = router;
