<?php

use App\Http\Controllers\Admin\Auth\AdminAuthController;
use App\Http\Controllers\Admin\Web\AuditLogController;
use App\Http\Controllers\Admin\Web\ClassicLudoTableController;
use App\Http\Controllers\Admin\Web\DashboardController;
use App\Http\Controllers\Admin\Web\GameController;
use App\Http\Controllers\Admin\Web\MatchMonitorController;
use App\Http\Controllers\Admin\Web\SupportTicketController;
use App\Http\Controllers\Admin\Web\TournamentController;
use App\Http\Controllers\Admin\Web\UserController;
use App\Http\Controllers\Admin\Web\HomepageCardController;
use App\Http\Controllers\Admin\Web\LegacyReportController;
use App\Http\Controllers\Admin\Web\DepositController;
use App\Http\Controllers\Admin\Web\WithdrawalController;
use App\Http\Controllers\Admin\Web\WalletTransactionController;
use App\Http\Controllers\Admin\Web\GatewayController;
use App\Http\Controllers\Admin\Web\SettingController;
use App\Http\Controllers\Admin\Web\AgentController;
use App\Http\Controllers\Admin\Web\DistributorController;
use Illuminate\Support\Facades\Route;

Route::middleware('web')->group(function () {
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::get('/login', [AdminAuthController::class, 'showLogin'])->name('login');
        Route::post('/login', [AdminAuthController::class, 'login'])->name('login.submit');

        Route::middleware(['admin.auth', 'admin.role:super_admin,admin'])->group(function () {
            Route::get('/', DashboardController::class)->name('dashboard');
            Route::get('/dashboard', DashboardController::class);
            Route::get('/games', [GameController::class, 'index'])->name('games.index');
            Route::post('/games/{game}', [GameController::class, 'update'])->name('games.update');
            Route::get('/games/ludo-tables', [ClassicLudoTableController::class, 'index'])->name('games.ludo-tables.index');
            Route::post('/games/ludo-tables', [ClassicLudoTableController::class, 'store'])->name('games.ludo-tables.store');
            Route::put('/games/ludo-tables/{classicLudoTable}', [ClassicLudoTableController::class, 'update'])->name('games.ludo-tables.update');
            Route::delete('/games/ludo-tables/{classicLudoTable}', [ClassicLudoTableController::class, 'destroy'])->name('games.ludo-tables.destroy');
            Route::get('/tournaments/create', [TournamentController::class, 'create'])->name('tournaments.create');
            Route::get('/tournaments/matches', [MatchMonitorController::class, 'index'])->name('tournaments.matches');
            Route::post('/tournaments/run-scheduler', [TournamentController::class, 'runScheduler'])->name('tournaments.run-scheduler');
            Route::get('/tournaments', [TournamentController::class, 'index'])->name('tournaments.index');
            Route::post('/tournaments', [TournamentController::class, 'store'])->name('tournaments.store');
            Route::get('/tournaments/{tournament}/edit', [TournamentController::class, 'edit'])->name('tournaments.edit');
            Route::get('/tournaments/{tournament}/report', [TournamentController::class, 'report'])->name('tournaments.report');
            Route::get('/tournaments/{tournament}/export', [TournamentController::class, 'export'])->name('tournaments.export');
            Route::get('/tournaments/{tournament}/print', [TournamentController::class, 'print'])->name('tournaments.print');
            Route::put('/tournaments/{tournament}', [TournamentController::class, 'update'])->name('tournaments.update');
            Route::post('/tournaments/{tournament}/approve', [TournamentController::class, 'approve'])->name('tournaments.approve');
            Route::post('/tournaments/{tournament}/reject', [TournamentController::class, 'reject'])->name('tournaments.reject');
            Route::post('/tournaments/{tournament}/force-live', [TournamentController::class, 'forceLive'])->name('tournaments.force-live');
            Route::post('/tournaments/{tournament}/fake-registrations', [TournamentController::class, 'adjustFakeRegistrations'])->name('tournaments.fake-registrations');
            Route::post('/matches/{match}/force-winner', [MatchMonitorController::class, 'forceWinner'])->name('matches.force-winner');
            Route::get('/users', [UserController::class, 'index'])->name('users.index');
            Route::get('/users/{user}/matches', [UserController::class, 'userMatches'])->name('users.matches');
            Route::get('/users/{user}', [UserController::class, 'show'])->name('users.show');
            Route::put('/users/{user}', [UserController::class, 'update'])->name('users.update');
            Route::post('/users/{user}/panel-permissions', [UserController::class, 'updatePanelPermissions'])->name('users.panel-permissions');
            Route::get('/support-tickets', [SupportTicketController::class, 'index'])->name('support.index');
            Route::get('/support-tickets/{ticket}', [SupportTicketController::class, 'show'])->name('support.show');
            Route::post('/support-tickets/{ticket}/reply', [SupportTicketController::class, 'reply'])->name('support.reply');
            Route::post('/support-tickets/{ticket}/status', [SupportTicketController::class, 'updateStatus'])->name('support.status');
            Route::get('/wallet-transactions', [WalletTransactionController::class, 'index'])->name('wallet-transactions.index');
            Route::get('/audit-logs', [AuditLogController::class, 'index'])->name('audit-logs.index');
            Route::get('/deposits', [DepositController::class, 'index'])->name('deposits.index');
            Route::post('/deposits/status', [DepositController::class, 'changeStatus'])->name('deposits.status');
            Route::get('/deposits/bonus', [DepositController::class, 'bonusIndex'])->name('deposits.bonus.index');
            Route::get('/deposits/bonus/create', [DepositController::class, 'bonusCreate'])->name('deposits.bonus.create');
            Route::post('/deposits/bonus', [DepositController::class, 'bonusStore'])->name('deposits.bonus.store');
            Route::get('/deposits/bonus/{bonus}/edit', [DepositController::class, 'bonusEdit'])->name('deposits.bonus.edit');
            Route::put('/deposits/bonus/{bonus}', [DepositController::class, 'bonusUpdate'])->name('deposits.bonus.update');
            Route::delete('/deposits/bonus/{bonus}', [DepositController::class, 'bonusDelete'])->name('deposits.bonus.delete');
            Route::get('/deposits/percentage', [DepositController::class, 'percentageIndex'])->name('deposits.percentage.index');
            Route::get('/deposits/percentage/create', [DepositController::class, 'percentageCreate'])->name('deposits.percentage.create');
            Route::post('/deposits/percentage', [DepositController::class, 'percentageStore'])->name('deposits.percentage.store');
            Route::get('/deposits/percentage/{percent}/edit', [DepositController::class, 'percentageEdit'])->name('deposits.percentage.edit');
            Route::put('/deposits/percentage/{percent}', [DepositController::class, 'percentageUpdate'])->name('deposits.percentage.update');
            Route::delete('/deposits/percentage/{percent}', [DepositController::class, 'percentageDelete'])->name('deposits.percentage.delete');
            Route::get('/withdrawals', [WithdrawalController::class, 'index'])->name('withdrawals.index');
            Route::post('/withdrawals/status', [WithdrawalController::class, 'changeStatus'])->name('withdrawals.status');
            Route::post('/withdrawals/transfer', [WithdrawalController::class, 'transferToBetzono'])->name('withdrawals.transfer');
            Route::get('/withdrawals/redeem', [WithdrawalController::class, 'redeemIndex'])->name('withdrawals.redeem.index');
            Route::get('/withdrawals/redeem/create', [WithdrawalController::class, 'redeemCreate'])->name('withdrawals.redeem.create');
            Route::post('/withdrawals/redeem', [WithdrawalController::class, 'redeemStore'])->name('withdrawals.redeem.store');
            Route::get('/withdrawals/redeem/{redeem}/edit', [WithdrawalController::class, 'redeemEdit'])->name('withdrawals.redeem.edit');
            Route::put('/withdrawals/redeem/{redeem}', [WithdrawalController::class, 'redeemUpdate'])->name('withdrawals.redeem.update');
            Route::delete('/withdrawals/redeem/{redeem}', [WithdrawalController::class, 'redeemDelete'])->name('withdrawals.redeem.delete');
            Route::get('/gateways/manual', [GatewayController::class, 'manualIndex'])->name('gateways.manual.index');
            Route::get('/gateways/manual/create', [GatewayController::class, 'manualCreate'])->name('gateways.manual.create');
            Route::post('/gateways/manual', [GatewayController::class, 'manualStore'])->name('gateways.manual.store');
            Route::get('/gateways/manual/{gateway}/edit', [GatewayController::class, 'manualEdit'])->name('gateways.manual.edit');
            Route::put('/gateways/manual/{gateway}', [GatewayController::class, 'manualUpdate'])->name('gateways.manual.update');
            Route::post('/gateways/manual/{gateway}/toggle', [GatewayController::class, 'manualToggleStatus'])->name('gateways.manual.toggle');
            Route::get('/gateways/agent', [GatewayController::class, 'agentIndex'])->name('gateways.agent.index');
            Route::get('/gateways/agent/create', [GatewayController::class, 'agentCreate'])->name('gateways.agent.create');
            Route::post('/gateways/agent', [GatewayController::class, 'agentStore'])->name('gateways.agent.store');
            Route::get('/gateways/agent/{gateway}/edit', [GatewayController::class, 'agentEdit'])->name('gateways.agent.edit');
            Route::put('/gateways/agent/{gateway}', [GatewayController::class, 'agentUpdate'])->name('gateways.agent.update');
            Route::get('/gateways/agent-withdraw', [GatewayController::class, 'agentWithdrawIndex'])->name('gateways.agent-withdraw.index');
            Route::get('/gateways/agent-withdraw/create', [GatewayController::class, 'agentWithdrawCreate'])->name('gateways.agent-withdraw.create');
            Route::post('/gateways/agent-withdraw', [GatewayController::class, 'agentWithdrawStore'])->name('gateways.agent-withdraw.store');
            Route::get('/gateways/agent-withdraw/{gateway}/edit', [GatewayController::class, 'agentWithdrawEdit'])->name('gateways.agent-withdraw.edit');
            Route::put('/gateways/agent-withdraw/{gateway}', [GatewayController::class, 'agentWithdrawUpdate'])->name('gateways.agent-withdraw.update');
            Route::get('/gateways/distributor', [GatewayController::class, 'distributorIndex'])->name('gateways.distributor.index');
            Route::get('/gateways/distributor/create', [GatewayController::class, 'distributorCreate'])->name('gateways.distributor.create');
            Route::post('/gateways/distributor', [GatewayController::class, 'distributorStore'])->name('gateways.distributor.store');
            Route::get('/gateways/distributor/{gateway}/edit', [GatewayController::class, 'distributorEdit'])->name('gateways.distributor.edit');
            Route::put('/gateways/distributor/{gateway}', [GatewayController::class, 'distributorUpdate'])->name('gateways.distributor.update');
            Route::get('/gateways/distributor-withdraw', [GatewayController::class, 'distributorWithdrawIndex'])->name('gateways.distributor-withdraw.index');
            Route::get('/gateways/distributor-withdraw/create', [GatewayController::class, 'distributorWithdrawCreate'])->name('gateways.distributor-withdraw.create');
            Route::post('/gateways/distributor-withdraw', [GatewayController::class, 'distributorWithdrawStore'])->name('gateways.distributor-withdraw.store');
            Route::get('/gateways/distributor-withdraw/{gateway}/edit', [GatewayController::class, 'distributorWithdrawEdit'])->name('gateways.distributor-withdraw.edit');
            Route::put('/gateways/distributor-withdraw/{gateway}', [GatewayController::class, 'distributorWithdrawUpdate'])->name('gateways.distributor-withdraw.update');
            Route::get('/settings/app', [SettingController::class, 'appConfiguration'])->name('settings.app');
            Route::post('/settings/app', [SettingController::class, 'updateAppConfiguration'])->name('settings.app.update');
            Route::get('/agents', [AgentController::class, 'index'])->name('agents.index');
            Route::get('/agents/create', [AgentController::class, 'create'])->name('agents.create');
            Route::post('/agents', [AgentController::class, 'store'])->name('agents.store');
            Route::get('/agents/{agent}/edit', [AgentController::class, 'edit'])->name('agents.edit');
            Route::put('/agents/{agent}', [AgentController::class, 'update'])->name('agents.update');
            Route::get('/agents/{agent}/users', [AgentController::class, 'users'])->name('agents.users');
            Route::get('/agents/{agent}/wallet/{type}', [AgentController::class, 'walletForm'])->name('agents.wallet.form');
            Route::post('/agents/{agent}/wallet', [AgentController::class, 'updateWallet'])->name('agents.wallet.update');
            Route::get('/agents/{agent}/wallet-logs', [AgentController::class, 'walletLogs'])->name('agents.wallet.logs');
            Route::get('/agents/{agent}/payment-methods', [AgentController::class, 'paymentMethods'])->name('agents.payment-methods');
            Route::get('/agents/{agent}/payment-methods/create', [AgentController::class, 'paymentMethodCreate'])->name('agents.payment-methods.create');
            Route::post('/agents/{agent}/payment-methods', [AgentController::class, 'paymentMethodStore'])->name('agents.payment-methods.store');
            Route::delete('/agents/{agent}/payment-methods/{method}', [AgentController::class, 'paymentMethodDelete'])->name('agents.payment-methods.delete');
            Route::get('/distributors', [DistributorController::class, 'index'])->name('distributors.index');
            Route::get('/distributors/create', [DistributorController::class, 'create'])->name('distributors.create');
            Route::post('/distributors', [DistributorController::class, 'store'])->name('distributors.store');
            Route::get('/distributors/{distributor}/edit', [DistributorController::class, 'edit'])->name('distributors.edit');
            Route::put('/distributors/{distributor}', [DistributorController::class, 'update'])->name('distributors.update');
            Route::get('/distributors/{distributor}/users', [DistributorController::class, 'users'])->name('distributors.users');
            Route::get('/distributors/{distributor}/wallet/{type}', [DistributorController::class, 'walletForm'])->name('distributors.wallet.form');
            Route::post('/distributors/{distributor}/wallet', [DistributorController::class, 'updateWallet'])->name('distributors.wallet.update');
            Route::get('/distributors/{distributor}/wallet-logs', [DistributorController::class, 'walletLogs'])->name('distributors.wallet.logs');
            Route::get('/distributors/{distributor}/payment-history', [DistributorController::class, 'paymentHistory'])->name('distributors.payment-history');
            Route::get('/legacy-reports', [LegacyReportController::class, 'index'])->name('legacy-reports.index');
            Route::get('/legacy-reports/purchase-history', [LegacyReportController::class, 'purchaseHistory'])->name('legacy-reports.purchase-history');
            Route::get('/legacy-reports/deposit-bonus', [LegacyReportController::class, 'depositBonus'])->name('legacy-reports.deposit-bonus');
            Route::get('/legacy-reports/bet-commission', [LegacyReportController::class, 'betCommission'])->name('legacy-reports.bet-commission');
            Route::get('/legacy-reports/rebate-history', [LegacyReportController::class, 'rebateHistory'])->name('legacy-reports.rebate-history');
            Route::get('/legacy-reports/welcome-bonus', [LegacyReportController::class, 'welcomeBonus'])->name('legacy-reports.welcome-bonus');
            Route::get('/legacy-reports/withdrawal-logs', [LegacyReportController::class, 'withdrawalLogs'])->name('legacy-reports.withdrawal-logs');
            Route::get('/legacy-reports/redeem-list', [LegacyReportController::class, 'redeemList'])->name('legacy-reports.redeem-list');

            // Homepage Tournament Cards
            Route::get('/homepage-cards',                        [HomepageCardController::class, 'index'])->name('homepage-cards.index');
            Route::post('/homepage-cards',                       [HomepageCardController::class, 'store'])->name('homepage-cards.store');
            Route::post('/homepage-cards/reorder',               [HomepageCardController::class, 'reorder'])->name('homepage-cards.reorder');
            Route::put('/homepage-cards/{homepageCard}',         [HomepageCardController::class, 'update'])->name('homepage-cards.update');
            Route::delete('/homepage-cards/{homepageCard}',      [HomepageCardController::class, 'destroy'])->name('homepage-cards.destroy');

            Route::post('/logout', [AdminAuthController::class, 'logout'])->name('logout');
        });
    });
});
